name: Toya Llorca
description: Web Developer
logo: logo-i.html
fold: nav

title: "Mi sitio"


nav-icons: 'true'

#Nav icons
navbutton:  'http://linkaloquequieras'
iconshop:  'http://linkalacesta'
iconsearch: 'true'



icontwitter: '#'
iconyoutube: '#'
iconpinterest: '#'
iconlinkedin: '#'


header:
  logo:
    position: 'left'
  menu:
    position: 'fixed'
  hero: 'true'
  top-bar: 'false'

no-hero:
  header:
    logo:
      position: 'left'
    menu:
      position: 'fixed'
    hero: 'false'
    top-bar: 'false'

logo-center:
  header:
    logo:
      position: 'center'
    menu:
        position: 'fixed'
    hero: 'true'
    top-bar: 'false'

logo-center-no-hero:
  header:
    logo:
      position: 'center'
    menu:
        position: 'fixed'
    hero: 'false'
    top-bar: 'false'

logo-right:
  header:
    logo:
      position: 'right'
    menu:
      position: 'fixed'
    hero: 'true'
    top-bar: 'false'



footer: "Lorem Ipsum dolor sit amet. 989 556 443. info@tldxilon.github.io"