name: Toya Llorca
description: Web Developer
logo: logo-i.html


nav-icons: 'true'

#Nav icons
navbutton:  'http://linkaloquequieras'
iconshop:  'http://linkalacesta'
iconsearch:  'inputsearch'



top-bar: 'false'

icontwitter: '#'
iconyoutube: '#'
iconpinterest: '#'
iconlinkedin: '#'



footer: "Lorem Ipsum dolor sit amet. 989 556 443. info@tldxilon.github.io"