name: Toya Llorca
description: Web Developer
logo: logo-i.html

title: "Mi sitio"

header:
  logo:
    file: http://dominio.es/milogo.png
    position: 'left'
  width: '-fluid'
  hero: 'true'

nav-icons: 'true'

#Nav icons
navbutton:  'http://linkaloquequieras'
iconshop:  'http://linkalacesta'
iconsearch:  '#searchbar'



top-bar: 'false'



icontwitter: '#'
iconyoutube: '#'
iconpinterest: '#'
iconlinkedin: '#'



footer: "Lorem Ipsum dolor sit amet. 989 556 443. info@tldxilon.github.io"