name: Toya Llorca
description: Web Developer
logo-image: 'logo2.png'
logo-title: ''


fold: nav

title: "Mi sitio"


nav-tools: 'true'

#Nav tools
navbutton:  'http://linkaloquequieras'
ecommerce:  'true'
iconsearch: 'true'
iconuser: 'true'


icontwitter: '#'
iconyoutube: '#'
iconpinterest: '#'
iconlinkedin: '#'






footer: "Lorem Ipsum dolor sit amet. 989 556 443. info@tldxilon.github.io"