name: Toya Llorca
description: Web Developer
logo: logo-i.html
fold: nav

title: "Mi sitio"


nav-icons: 'true'

#Nav icons
navbutton:  'http://linkaloquequieras'
iconshop:  'http://linkalacesta'
iconsearch: 'true'



icontwitter: '#'
iconyoutube: '#'
iconpinterest: '#'
iconlinkedin: '#'


options:
  logo-left:
  logo-left-2:




logo-left:
  header:
    logo:
      position: 'left'
      size: 'm'
      padding: 'xs'
    menu:
      position: 'right'
      style: 'navbar-menu--back'
    hero: 'true'
    top-bar: 'false'
    container: 'container-fluid'


logo-center:
  header:
    logo:
      position: 'top'
      size: 'm'
      padding: 'l'
    menu:
      position: 'center'
    hero: 'true'
    top-bar: 'false'



logo-right:
  header:
    logo:
      position: 'right'
      size: 'm'
    menu:
      position: 'left'
    hero: 'true'
    top-bar: 'false'
    container: 'container'



footer: "Lorem Ipsum dolor sit amet. 989 556 443. info@tldxilon.github.io"